export const ADD_CONTENT = "ADD_CONTENT"
export const GET_CONTENT = "GET_CONTENT"
export const UPDATE_CONTENT = "UPDATE_CONTENT"
export const DELETE_CONTENT = "DELETE_CONTENT"
export const LAST_UPLOAD = "LAST_UPLOAD"
export const FIRST_UPLOAD = "FIRST_UPLOAD"
export const NAME_A_TO_Z = "NAME_A_TO_Z"
export const TRENDING_BANDS = "TRENDING_BANDS"
export const ALL_TIME_POPULAR = "ALL_TIME_POPULAR"




